# Generated by Django 2.2 on 2019-04-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_auto_20190425_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.ManyToManyField(to='quest.Answers', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.TextField(max_length=400, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Количесвто голосов'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_text',
            field=models.TextField(max_length=400, verbose_name='Вопрос'),
        ),
    ]
