# Generated by Django 2.2 on 2019-04-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_auto_20190425_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RemoveField(
            model_name='room',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='room',
            name='invited',
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.AddField(
            model_name='questions',
            name='answers',
            field=models.ManyToManyField(related_name='ans_the_quest', to='quest.Answer', verbose_name='Ответ'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
