# Generated by Django 2.2 on 2019-04-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_auto_20190425_2106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Answers',
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['id']},
        ),
    ]
