# Generated by Django 2.2 on 2019-04-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0009_auto_20190425_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='AnswersModel',
        ),
    ]
