# Generated by Django 2.2 on 2019-04-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0010_auto_20190425_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField(verbose_name='Ответы на вопросы')),
            ],
        ),
        migrations.RemoveField(
            model_name='answersmodel',
            name='votes',
        ),
    ]
